name: ThisIsFiction
favicon: null
layout_spectrum: 0.4546637269668281
typography_spectrum: 0.9257862814702094
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9275470417924225
  lightness: 0.12364530563354492
  saturation: 0.5683040856383741
  rhythmicContrast: 0.5500341311562806
purpose: []
